### ISSUE TITLE
Possible to fetch galnet news in other languages? 

### ISSUE THREAD

**Issue by compumark** [pluginpatch/galnet-discord-bot#1]
Is it possible that the bot fetches with a configuration also eg. german language galnet news instead of the english ones?

Here is an example:

this is the link from a posting from a galnet news bot entry:
https://community.elitedangerous.com/galnet/uid/623aee1d75f7e20cd02d4c51

this is the german available version of the entry:
https://community.elitedangerous.com/de/galnet/uid/623aee1d75f7e20cd02d4c51

Would be great to have this included.

**Comment by pluginpatch** [comment]
👋 Hey, I've added new language preference configuration.

To update your new language preference simply add the language code to your channel topic, ie `galnet-news on de-DE`
I've included some more details, including the allowable language codes on the readme. Please reach out if there are any issues or any other requested languages.

Thanks for some feedback on the bot, I'm happy to hear others are using it 😄 

https://github.com/pluginpatch/galnet-discord-bot/commit/65efede8bfbaae986528eb3becaff4b2f13ba6ba
https://github.com/pluginpatch/galnet-discord-bot/commit/e07420f6804661c3c7930cf3864912f217c61420

**Comment by compumark** [comment]
I updated the channel code now and are waiting for the next galnet entry :-)
I will provide a feedback here.

**Comment by compumark** [comment]
Now the first next article was published, but still in english
I stopped it now with galnet-news off and enabled it again with galnet-news on de-DE and waiting for the next article to be pushed.

**Comment by pluginpatch** [comment]
Hey, I can also confirm that I am not seeing it sync in the correct language. Looking on the backend, I can confirm that the language is correctly set. I'm looking into this and I should update soon. Apologies for the back and forth.

**Comment by pluginpatch** [comment]
👋 Hey again, I _think_ I got this working now. I'll be monitoring any new updates for now. Once a new article publishes, please let me know if you are seeing things post in the correct language. 

I'll update again when I see a successful post. Thanks!

**Comment by compumark** [comment]
looks good now: 
![image](https://user-images.githubusercontent.com/75847830/161063995-40186791-682d-44cb-9949-2182a5dd8ee7.png)

**Comment by pluginpatch** [comment]
🙌 Great! Thank you for confirming. Thank you again for working with me and the feedback on the bot! Please share the bot with other discord server owners who may find it beneficial!

Ref: https://github.com/pluginpatch/galnet-discord-bot/commit/15776a3745a97b538dd8d32d0cac78b377c19524
