### ISSUE TITLE
Fetch in german not working

### ISSUE THREAD

**Issue by compumark** [pluginpatch/galnet-discord-bot#2]
The messages are still appearing in English
![image](https://user-images.githubusercontent.com/75847830/160662040-dac957cd-7691-4b93-83ce-4063cd405440.png)

**Comment by pluginpatch** [comment]
👋 Hey, it looks like my update on https://github.com/pluginpatch/galnet-discord-bot/issues/1 did not fix the issue. I am continuing to work on the issue on that thread. I'm going to close this one as a duplicate.
