### ISSUE TITLE
Complete Archive?

### ISSUE THREAD

**Issue by StarGoid** [pluginpatch/galnet-discord-bot#8]
Firstly:  thanks for creating this.  We use it on our discord, and we love it.

I'm hoping you can help me - i'm trying to create a complete archive (in a single file) of all galnet articles.  But - as you can imagine - that's turning out to be rather difficult.  I initially thought I'd just copy/paste directly from the official website for galnet.  But that is 300 pages (plus) long.  So that seems like an incredibly time consuming.
I looked into using a web scraper - but with limited coding skills - that's turned out to be a whole new challenge.  So - I thought - before I go trying to venture down that road I'd reach out for some help/advice from someone who understands the API etc.

Can you perhaps point me in the right direction?

**Comment by pluginpatch** [comment]
@StarGoid I'm glad to hear you use the bot! I haven't worked on this code is quite some time. But you should be able to pull all the articles you'd like through the API. For example, to get the most recent article with a limit of 20: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article?&sort=-published_at&page[offset]=0&page[limit]=20

You should be able to page through all the articles somewhat quickly by using this URL. It'll take some extra logging to save all the articles to your local. I don't mind helping you out, but I'm not sure what exactly you are using or what the end product looks like. I'm open to assisting you, you can reach out to me on discord @pluginpatch. But, I'll close out this request for now

**Comment by CMDRCuzz** [comment]
Hi, is there an issue with the bot. It doesn’t seem to be updating on my Discord server, I have been able to get latest articles using the get now command but nothing is coming through otherwise.
