### ISSUE TITLE
Not not updating articles 

### ISSUE THREAD

**Issue by CMDRCuzz** [pluginpatch/galnet-discord-bot#9]
Hi, is there an issue with the bot. It doesn’t seem to be updating on my Discord server, I have been able to get latest articles using the get now command but nothing is coming through otherwise.

**Comment by pluginpatch** [comment]
Hi @CMDRCuzz 

I'm looking at the logs, and I am seeing the articles posting as normal. But I would like to investigate further. Could you please provide your Discord server name and channel name?

Here is an example of a recent post:
`[Mar 12, 2024, 11:07:02 AM] Posting article: {guild: "GalNet", channel: "news"}`

With your Discord server name and channel name I can check to see if there is a reason why it isn't posting in your server.

Thanks!

**Comment by CMDRCuzz** [comment]
Hi, the Discord server is The Elite Pilot’s Group, channel Galnet News.Kind Regards,Andy Cousin.07542 642655.On 14 Mar 2024, at 06:45, pluginpatch ***@***.***> wrote:﻿
Hi @CMDRCuzz
I'm looking at the logs, and I am seeing the articles posting as normal. But I would like to investigate further. Could you please provide your Discord server name and channel name?
Here is an example of a recent post:
[Mar 12, 2024, 11:07:02 AM] Posting article: {guild: "GalNet", channel: "news"}
With your Discord server name and channel name I can check to see if there is a reason why it isn't posting in your server.
Thanks!

**Comment by pluginpatch** [comment]
Hi @CMDRCuzz 

I don't see your Discord server in the system. I suggest the following:

1. Kick the bot from the Discord server and re-add. 
2. Add `galnet-news on` in the channel topic.
3. Make sure the bot has correct permissions. 

If this doesn't work, I can try to assist you further over Discord. You can contact me at username: `pluginpatch`

Thanks!

**Comment by CMDRCuzz** [comment]
Kicked the bot and re added now, let’s see if that now works. Many thanks for your help.Kind Regards,Andy Cousin.07542 642655On 14 Mar 2024, at 21:26, pluginpatch ***@***.***> wrote:﻿
Hi @CMDRCuzz
I don't see your Discord server in the system. I suggest the following:

Kick the bot from the Discord server and re-add.
Add galnet-news on in the channel topic.
Make sure the bot has correct permissions.

If this doesn't work, I can try to assist you further over Discord. You can contact me at username: pluginpatch
Thanks!
